[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.75
blur = true
startup_mode = "Maximized"
level = "AlwaysOnTop"
option_as_alt = "Both"

[font]
size = 12
normal = { family = "Hack Nerd Font Mono" }

[terminal]
shell = { program = "/opt/homebrew/bin/zellij" }

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
